apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          env:
            - name: Username
              value: Administrator
            - name: Password
              value: MyDiReCtP@sSw0rd               # NOT GOOD
          ports:
            - containerPort: 80
              name: web